# Generated by Django 2.2.1 on 2019-07-20 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20190717_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=264)),
                ('number', models.IntegerField()),
                ('nghhood', models.CharField(max_length=264)),
                ('cep', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=264)),
                ('price', models.FloatField()),
                ('descrition', models.TextField(max_length=500)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Address')),
            ],
        ),
    ]
