# Generated by Django 2.2.1 on 2019-07-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_address_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
